### ISSUE TITLE
compatibility with redmine 5

### ISSUE THREAD

**Issue by SinghNanak** [xmera-circle/redmine_project_types#1]

**Comment by SinghNanak** [comment]
@liaham any clue when will this plugin become compatible with redmine 5

**Comment by liaham** [comment]
Hi @nanaksingh13,

Thank you for your request. 🙂

We're planning to release the new version supporting Redmine 5 around beginnig of April.

Best Regards,
@liaham

**Comment by SinghNanak** [comment]
any updates
